<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        //'ZendDeveloperTools', // esta linha gera a barra ZendDeveloperTools no rodapé
        'DoctrineModule',
        'DoctrineORMModule',
        'ZfcBase',
        'ZfcUser',
        'ZfcUserDoctrineORM',
        'ZfcRbac',
        'TwbBundle',
        'Application',
        //'Test',
        //'LearnZF2AjaxImageGallery',
        //'ZF2FileUploadExamples',
        //'LearnZF2Pagination',
        //'DOMPDFModule',
        'Api',
        ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
    ),
);
