<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle()->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo
    $this->headLink(
        array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'
        )
        )
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>

    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        // trouxe pra localhost ->prependFile('https://code.jquery.com/jquery.js');
        ->prependFile($this->basePath() . '/js/jquery/jquery.js');
    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!--
    Layout: module/Application/view/layout/layout.phtml
    -->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse col-lg-push-6 col-md-push-6 col-sx-push-0">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->translate('User') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('post') ?>"><?php echo $this->translate('Blog') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('produto') ?>">Produto</a></li>
                        <li class="active">
                            <a href="<?php echo $this-> basePath("fornecedor"); ?>">
                                Fornecedor
                            </a>
                        </li>
                    </ul>
                    <?php // echo $this->navigation('Navigation')->menu()->setUlClass('nav navbar-nav'); ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
    </div>

    <div class="container">
        <?php echo $this->content; ?>
        <hr>
        <footer>
            <p>&copy; 2005 - <?php echo date('Y') ?> by AXM Consultoria. Todos os diritos reservados</p>
        </footer>
    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
</body>
</html>
